### ISSUE TITLE
How to hide error text

### ISSUE THREAD

**Issue by gianmarcogg03** [quelotic/polybarModules#1]
On the mail module how do I hide this error text or to at least change it to something custom that appears when it fails to reach the server?
![2021-11-05_08-58](https://user-images.githubusercontent.com/28053717/140902559-90234e65-c950-4003-9c73-d8fbf4feb187.png)

**Comment by quelotic** [comment]
You can wrap the code inside a try/except statement. Inside the except you can print the message you want to show in case of an error. Have a read of the [python docs](https://docs.python.org/3/tutorial/errors.html).
